# Generated by Django 5.0.6 on 2024-06-28 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_no', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('region', models.CharField(choices=[('North', 'North'), ('South', 'South')], max_length=100)),
                ('ia_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('po_no', models.CharField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=500)),
                ('delivery_date', models.DateField()),
                ('ia_sub', models.DateField()),
                ('inspection_date', models.DateField()),
                ('vendor_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.vendors')),
            ],
        ),
    ]
