# Generated by Django 5.0.6 on 2024-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='ia_sub',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='inspection_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='ia_date',
            field=models.DateField(null=True),
        ),
    ]
