# Generated by Django 5.0.6 on 2024-07-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_purchaseorders_ia_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DocName', models.CharField(max_length=255)),
                ('Doc', models.FileField(blank=True, null=True, upload_to='app_main/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorNo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('VendorName', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=254)),
                ('Territory', models.CharField(max_length=255)),
                ('IaAlertDays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PONO', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ShipDate', models.DateField()),
                ('Customer', models.CharField(max_length=255)),
                ('IaSubmissionDate', models.DateField()),
                ('InspectionDate', models.DateField(null=True)),
                ('VendorNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseOrders',
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
