# Generated by Django 5.0.6 on 2024-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_document_vendor_purchaseorder_delete_purchaseorders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='InspectionDateProposed',
            field=models.DateField(null=True),
        ),
    ]
