# Generated by Django 5.0.6 on 2024-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_purchaseorder_inspectiondateproposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Status',
            field=models.CharField(default='Inspection date to be submitted'),
        ),
    ]
