# Generated by Django 5.0.6 on 2024-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Alerts',
            field=models.CharField(null=True),
        ),
    ]
